CREATE DATABASE IF NOT EXISTS EMPYMTDB;
USE EMPYMTDB

CREATE TABLE EMPYMTDB.EMPLOYEE (
    ID VARCHAR(20) NOT NULL,
    LOGIN VARCHAR(40) NOT NULL,
    NAME VARCHAR(60) NOT NULL,
    SALARY DECIMAL (20,2) NOT NULL,
    VERSION DECIMAL(10) NOT NULL,
	DTE_UPDATED DATETIME NOT NULL ,
	DTE_CREATED DATETIME NOT NULL,
    PRIMARY KEY (ID) 
);

CREATE TABLE EMPYMTDB.ID_GENERATOR (
    ID INT(19) NOT NULL AUTO_INCREMENT,
	DTE_CREATED DATETIME NOT NULL,
    PRIMARY KEY (ID) 
);